# Files which are filtered out from those defined by sonar.sources
sonar.exclusions=**/dependency-check-report.*,**/src/assets/**,**/src/environments/**

sonar.cpd.exclusions=**/app.component.*,**/contest-vote-detail-ballot.component.html,**/*-bundle-table.component.*,\
  **/*-ballot-review.component.*,**/*-bundle-info.component.*,**/*-end-result.component.*,**/proportional-election-unmodified-lists.component.html,\
  **/majority-election-ballot-groups.component.html,**/*-bundle-overview.component.*,**/*-ballot.component.*
